[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Joshua Radin <jradin16@gmail.com>"]
version = "0.0.0"
edition = "2021"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/joshradin/aroma"


