[package]
name = "aroma_vm"
authors.workspace = true
version.workspace = true
edition.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
aroma_gc = { version = "0.0.0", path = "../aroma_gc", features = ["derive"] }
bitfield = "0.15.0"
bytes = "1.6.1"
nom = "7.1.3"
parking_lot = "0.12.3"
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "1.0.63"
